% \n");
% fprintf("

fprintf("To crop the same amount of non-faces, a random image from the folder is loaded, then a random \n");
fprintf("point in the image is selected as the starting point, 36 columns and 36 rows are extracted and \n");
fprintf("saved onto a new image file. This fulfills step 1.1.\n\n");
fprintf("Step 1.2 is fulfilled later.\n\n");
fprintf("Next in get_features.m, a slight code modification is made to adjust matrix generated by a \n");
fprintf("different cell size. This fulfills step 1.3\n\n");
fprintf("Next in train_svm.m, the dataset is sliced into 5 folds, 4 as training and 1 as testing, \n");
fprintf("taking turns to be the test fold, then the whole process repeats again. This performs the \n");
fprintf("repeated kfold cross validation. The accuracy is average with highestAcc keeping track of \n");
fprintf("the Weight and Bias with the highest accuracy; the values are saved into my_svm.mat at the \n");
fprintf("end. This fulfills steps 1.2, 1.4 and 1.5.\n\n");
fprintf("To improve scores from the confusion matrix: cell size and lambda has been lowered to 3 and \n");
fprintf("0.0001; Non-faces are randomly selected, generated, and transposed; and faces are randomly \n");
fprintf("horizontally flipped. The average accuracy is 0.9977 with a highest accuracy of 0.99963.\n\n");
